// <auto-generated />
using System;
using HeThongQuanLyKhoaHocVaDangKy_3_UNETI3_TIN17A2HN.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeThongQuanLyKhoaHocVaDangKy_3_UNETI3_TIN17A2HN.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260928024010_InitialCreate_Module1_UNETI")]
    partial class InitialCreate_Module1_UNETI
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HeThongQuanLyKhoaHocVaDangKy_3_UNETI3_TIN17A2HN.Models.DangKyKhoaHoc", b =>
                {
                    b.Property<int>("MaDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDangKy"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaHocVien")
                        .HasColumnType("int");

                    b.Property<int>("MaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXacNhan")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoTienConLai")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SoTienDaDong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDangKy");

                    b.HasIndex("MaHocVien");

                    b.HasIndex("MaKhoaHoc");

                    b.ToTable("DangKyKhoaHoc");
                });

            modelBuilder.Entity("HeThongQuanLyKhoaHocVaDangKy_3_UNETI3_TIN17A2HN.Models.GiangVien", b =>
                {
                    b.Property<int>("MaGiangVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiangVien"));

                    b.Property<string>("ChuyenMon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HocVi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaGiangVien");

                    b.ToTable("GiangVien");
                });

            modelBuilder.Entity("HeThongQuanLyKhoaHocVaDangKy_3_UNETI3_TIN17A2HN.Models.HocVien", b =>
                {
                    b.Property<int>("MaHocVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHocVien"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("TrinhDo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaHocVien");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique()
                        .HasFilter("[MaTaiKhoan] IS NOT NULL");

                    b.ToTable("HocVien");
                });

            modelBuilder.Entity("HeThongQuanLyKhoaHocVaDangKy_3_UNETI3_TIN17A2HN.Models.KetQuaHocTap", b =>
                {
                    b.Property<int>("MaKetQua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKetQua"));

                    b.Property<decimal>("DiemChuyenCan")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("DiemCuoiKy")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("DiemGiuaKy")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("DiemTongKet")
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("KetQua")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaDangKy")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<string>("XepLoai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaKetQua");

                    b.HasIndex("MaDangKy")
                        .IsUnique();

                    b.ToTable("KetQuaHocTap");
                });

            modelBuilder.Entity("HeThongQuanLyKhoaHocVaDangKy_3_UNETI3_TIN17A2HN.Models.KhoaHoc", b =>
                {
                    b.Property<int>("MaKhoaHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhoaHoc"));

                    b.Property<string>("HinhThuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("HocPhi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaGiangVien")
                        .HasColumnType("int");

                    b.Property<int>("MaMonHoc")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuongToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaKhoaHoc");

                    b.HasIndex("MaGiangVien");

                    b.HasIndex("MaMonHoc");

                    b.ToTable("KhoaHoc");
                });

            modelBuilder.Entity("HeThongQuanLyKhoaHocVaDangKy_3_UNETI3_TIN17A2HN.Models.MonHoc", b =>
                {
                    b.Property<int>("MaMonHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMonHoc"));

                    b.Property<decimal>("HocPhi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoTinChi")
                        .HasColumnType("int");

                    b.Property<string>("TenMonHoc")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaMonHoc");

                    b.HasIndex("TenMonHoc")
                        .IsUnique();

                    b.ToTable("MonHoc");
                });

            modelBuilder.Entity("HeThongQuanLyKhoaHocVaDangKy_3_UNETI3_TIN17A2HN.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("HeThongQuanLyKhoaHocVaDangKy_3_UNETI3_TIN17A2HN.Models.DangKyKhoaHoc", b =>
                {
                    b.HasOne("HeThongQuanLyKhoaHocVaDangKy_3_UNETI3_TIN17A2HN.Models.HocVien", "HocVien")
                        .WithMany("DangKyKhoaHocs")
                        .HasForeignKey("MaHocVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeThongQuanLyKhoaHocVaDangKy_3_UNETI3_TIN17A2HN.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("DangKyKhoaHocs")
                        .HasForeignKey("MaKhoaHoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HocVien");

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("HeThongQuanLyKhoaHocVaDangKy_3_UNETI3_TIN17A2HN.Models.HocVien", b =>
                {
                    b.HasOne("HeThongQuanLyKhoaHocVaDangKy_3_UNETI3_TIN17A2HN.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("HocVien")
                        .HasForeignKey("HeThongQuanLyKhoaHocVaDangKy_3_UNETI3_TIN17A2HN.Models.HocVien", "MaTaiKhoan");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("HeThongQuanLyKhoaHocVaDangKy_3_UNETI3_TIN17A2HN.Models.KetQuaHocTap", b =>
                {
                    b.HasOne("HeThongQuanLyKhoaHocVaDangKy_3_UNETI3_TIN17A2HN.Models.DangKyKhoaHoc", "DangKyKhoaHoc")
                        .WithOne("KetQuaHocTap")
                        .HasForeignKey("HeThongQuanLyKhoaHocVaDangKy_3_UNETI3_TIN17A2HN.Models.KetQuaHocTap", "MaDangKy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DangKyKhoaHoc");
                });

            modelBuilder.Entity("HeThongQuanLyKhoaHocVaDangKy_3_UNETI3_TIN17A2HN.Models.KhoaHoc", b =>
                {
                    b.HasOne("HeThongQuanLyKhoaHocVaDangKy_3_UNETI3_TIN17A2HN.Models.GiangVien", "GiangVien")
                        .WithMany("KhoaHocs")
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeThongQuanLyKhoaHocVaDangKy_3_UNETI3_TIN17A2HN.Models.MonHoc", "MonHoc")
                        .WithMany("KhoaHocs")
                        .HasForeignKey("MaMonHoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("HeThongQuanLyKhoaHocVaDangKy_3_UNETI3_TIN17A2HN.Models.DangKyKhoaHoc", b =>
                {
                    b.Navigation("KetQuaHocTap");
                });

            modelBuilder.Entity("HeThongQuanLyKhoaHocVaDangKy_3_UNETI3_TIN17A2HN.Models.GiangVien", b =>
                {
                    b.Navigation("KhoaHocs");
                });

            modelBuilder.Entity("HeThongQuanLyKhoaHocVaDangKy_3_UNETI3_TIN17A2HN.Models.HocVien", b =>
                {
                    b.Navigation("DangKyKhoaHocs");
                });

            modelBuilder.Entity("HeThongQuanLyKhoaHocVaDangKy_3_UNETI3_TIN17A2HN.Models.KhoaHoc", b =>
                {
                    b.Navigation("DangKyKhoaHocs");
                });

            modelBuilder.Entity("HeThongQuanLyKhoaHocVaDangKy_3_UNETI3_TIN17A2HN.Models.MonHoc", b =>
                {
                    b.Navigation("KhoaHocs");
                });

            modelBuilder.Entity("HeThongQuanLyKhoaHocVaDangKy_3_UNETI3_TIN17A2HN.Models.TaiKhoan", b =>
                {
                    b.Navigation("HocVien");
                });
#pragma warning restore 612, 618
        }
    }
}
